services:
  postgres:
    image: postgres:16-alpine
    container-name: ecom-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecom
    ports: 
     - "5432:5432"
    volumes:
     - postgres-data:/var/lib/postgres/data

volumes:
  postgres-data: